version: '3.8'
services:
  db:
    restart: always
    image: postgres:14-alpine
    user: postgres
    container_name: postgres-note
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: f85859852
      POSTGRES_DB: aurora_note
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgres/main-data
  testdb:
    image: postgres:14-alpine
    user: postgres
    container_name: postgres-note-test
    volumes:
      - data:/var/lib/postgres/test-data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: f85859852
      POSTGRES_DB: aurora_note_test
    ports:
      - 5480:5432
  
volumes:
  data:
    driver: local      